# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/dictation',
                'doc_host': 'https://simon-lawyer.github.io',
                'git_url': 'https://github.com/simon-lawyer/dictation',
                'lib_path': 'dictation'},
  'syms': {'dictation.core': {'dictation.core.foo': ('core.html#foo', 'dictation/core.py')}}}